In [1]:
from google.colab import files
uploaded = files.upload()

Saving Document_QA_RAG_AgenticX.pdf to Document_QA_RAG_AgenticX.pdf

In [2]:
import os
print(os.listdir())

['.config', 'Document_QA_RAG_AgenticX.pdf', 'sample_data']

In [3]:
!pip install -q pypdf sentence-transformers faiss-cpu transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 47.3 MB/s eta 0:00:00

In [4]:
from pypdf import PdfReader

pdf_path = list(uploaded.keys())[0]

reader = PdfReader(pdf_path)

print("Number of pages:", len(reader.pages))

Number of pages: 136

In [5]:
text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text + "\n"

print("Characters extracted:", len(text))
print(text[:2000])

Characters extracted: 381410
DIGITAL PROGRESS AND TRENDS REPORT 2025
STRENGTHENING
AI FOUNDATIONS
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Digital Progress and
Trends Report 2025
This book, along with any associated content or subsequent updates,
can be accessed at https://hdl.handle.net/10986/43822.
Scan to see all titles in this collection.
Digital Progress and
Trends Report 2025
Strengthening AI Foundations
© 2025 International Bank for Reconstruction and Development / The World Bank
1818 H Street NW, Washington, DC 20433
Telephone: 202-473-1000; Internet: www.worldbank.org
Some rights reserved
1 2 3 4  28 27 26 25
This work is a product of the staff of The World Bank with external contributions. The findings, interpretations, and
conclusions expressed in this work do not necessarily reflect the views of The World Bank, its Board of Executive Directors,
or the governments they represent.
The World Bank does not guarantee the accuracy, completeness, or currency of the data included in this work and does
not assume responsibility for any errors, omissions, or discrepancies in the information, or liability with respect to the use
of or failure to use the information, methods, processes, or conclusions set forth. The boundaries, colors, denominations,
links/footnotes, and other information shown in this work do not imply any judgment on the part of The World Bank
concerning the legal status of any territory or the endorsement or acceptance of such boundaries. The citation of works
authored by others does not mean The World Bank endorses the views expressed by those authors or the content of their
works.
Nothing herein shall constitute or be construed or considered to be a limitation upon or waiver of the privileges and
immunities of The World Bank, all of which are specifically reserved.
Rights and Permissions
This work is available under the Creative Commons Attribution 3.0 IGO license (CC BY 3.0 IGO) http

In [7]:
!pip install -q langchain-text-splitters

In [8]:
from langchain_text_splitters import CharacterTextSplitter

text_splitter_1 = CharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100
)

chunks_1 = text_splitter_1.split_text(text)

print("Number of chunks:", len(chunks_1))
print("\nFirst chunk:\n")
print(chunks_1[0])

Number of chunks: 1

First chunk:

DIGITAL PROGRESS AND TRENDS REPORT 2025
STRENGTHENING
AI FOUNDATIONS
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Digital Progress and
Trends Report 2025
This book, along with any associated content or subsequent updates,
can be accessed at https://hdl.handle.net/10986/43822.
Scan to see all titles in this collection.
Digital Progress and
Trends Report 2025
Strengthening AI Foundations
© 2025 International Bank for Reconstruction and Development / The World Bank
1818 H Street NW, Washington, DC 20433
Telephone: 202-473-1000; Internet: www.worldbank.org
Some rights reserved
1 2 3 4  28 27 26 25
This work is a product of the staff of The World Bank with external contributions. The findings, interpretations, and
conclusions expressed in this work do not necessarily reflect the views of The World Bank, its Board of Executive Directors,
or the governments they represent.
The World Bank does not guarantee the accuracy, completeness, or currency of the data included in this work and does
not assume responsibility for any errors, omissions, or discrepancies in the information, or liability with respect to the use
of or failure to use the information, methods, processes, or conclusions set forth. The boundaries, colors, denominations,
links/footnotes, and other information shown in this work do not imply any judgment on the part of The World Bank
concerning the legal status of any territory or the endorsement or acceptance of such boundaries. The citation of works
authored by others does not mean The World Bank endorses the views expressed by those authors or the content of their
works.
Nothing herein shall constitute or be construed or considered to be a limitation upon or waiver of the privileges and
immunities of The World Bank, all of which are specifically reserved.
Rights and Permissions
This work is available under the Creative Commons Attribution 3.0 IGO license (CC BY 3.0 IGO) http://creativecommons.
org/licenses/by/3.0/igo . Under the Creative Commons Attribution license, you are free to copy, distribute, transmit, and
adapt this work, including for commercial purposes, under the following conditions:
Attribution —Please cite the work as follows: World Bank. 2025. Digital Progress and Trends Report 2025: Strengthening
AI Foundations.  Washington, DC: World Bank. doi: 10.1596/978-1-4648-2264-3. License: Creative Commons Attribution
CC BY 3.0 IGO
Translations—If you create a translation of this work, please add the following disclaimer along with the attribution:  This
translation was not created by The World Bank and should not be considered an official World Bank translation.
The World Bank shall not be liable for any content or error in this translation.
Adaptations —If you create an adaptation of this work, please add the following disclaimer along with the attribution: This
is an adaptation of an original work by The World Bank. Views and opinions expressed in the adaptation are the sole
responsibility of the author or authors of the adaptation and are not endorsed by The World Bank.
Third-party content —The World Bank does not necessarily own each component of the content contained within the work.
The World Bank therefore does not warrant that the use of any third-party-owned individual component or part contained
in the work will not infringe on the rights of those third parties. The risk of claims resulting from such infringement rests
solely with you. If you wish to re-use a component of the work, it is your responsibility to determine whether permission is
needed for that re-use and to obtain permission from the copyright owner. Examples of components can include, but are
not limited to, tables, figures, or images.
All queries on rights and licenses should be addressed to World Bank Publications, The World Bank, 1818 H Street NW,
Washington, DC 20433, USA; e-mail: pubrights@worldbank.org .
ISBN (paper): 978-1-4648-2264-3
ISBN (electronic): 978-1-4648-2265-0
DOI: 10.1596/978-1-4648-2264-3
Cover images: AI professions set: artificial intelligence workers, machine learning, software engineers, digital data
analyst, robotics specialists, scientists. Flat vector illustration isolated on white background, by Good Studios, from
Adobe Stock. Further permission required for reuse.
Cover design: Veronical Elena Gadea / World Bank Group
Interior design: William Pragluski, Critical Stages LLC
Library of Congress Control Number: The Library of Congress Control Number has been requested.
  v
Contents
Foreword ..................................................................... ix
Acknowledgments .............................................................. xi
Main Messages  ............................................................... xiii
Abbreviations ................................................................ xvii
Chapter 1 H arnessing AI for Development: Can It Work?   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 1
Key Messages ...................................................... 1
AI definitions, ecosystem, and significant trends  ........................... 2
Scope of this report  ................................................. 5
Potential impacts of AI on the global economy and society  ................... 5
Uneven progress in AI innovation, adaptation, and adoption ................. 11
4C pillars of AI foundations .......................................... 20
About this publication .............................................. 21
Notes ........................................................... 21
References  ....................................................... 22
Chapter 2 Connectivity  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25
Key Messages ..................................................... 25
Digital infrastructure  ............................................... 26
Digital sector development ........................................... 28
Digital adoption ................................................... 31
How to ensure digital connectivity and adoption .......................... 37
Notes ........................................................... 37
References  ....................................................... 38
Chapter 3 Compute  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 39
Key Messages ..................................................... 39
Introduction ...................................................... 40
Supply: Market structure, growth, and sustainability  ...................... 40
Demand: Compute access modality and trade-offs  ......................... 43
vi  DIGITAL PROGRESS AND TRENDS REPORT 2025
Compute divide  ................................................... 44
How can countries achieve secure, equitable, and sustainable access to compute? ... 48
How can countries address the compute barrier? .......................... 51
Notes ........................................................... 54
References  ....................................................... 54
Chapter 4 C ontext: Training Data and AI Model Adaptation   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 57
Key Messages ..................................................... 57
Introduction ...................................................... 58
Effective AI models hinge on training data  ............................... 58
Data divide across countries and languages  .............................. 61
Adaptation of AI models to the national context  .......................... 66
Conclusion ....................................................... 68
Note ............................................................ 69
References  ....................................................... 69
Chapter 5 C ompetency: Digital Skills   . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 71
Key Messages ..................................................... 71
Introduction ...................................................... 72
Digitalization of occupations ......................................... 73
Demand for digital skills  ............................................ 75
Supply of digital skills  .............................................. 81
Policy insights to bridge the digital skills gap ............................. 86
Notes ........................................................... 88
References  ....................................................... 89
Chapter 6 Conclusion  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 91
Urgency for policy action ............................................ 91
Investing in the 4Cs ................................................ 92
Fiscal policy: Reducing inequality and providing a safety net amid potential
disruptions .................................................... 96
Labor and education policy: Future-proofing workers  ...................... 96
Managing AI risks through trustworthy and responsible AI systems  ........... 97
Notes ........................................................... 98
References  ....................................................... 99
Appendix A: Thematic Case Study Summaries  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 101
 CONTENTS   vii
Figures
1.1 K ey layers and segments of the AI ecosystem  ................................ 3
1.2 A I innovation and adaptation activities, by country income group  .............. 12
1.3 C hatGPT and GenAI traffic over time, by income level and country  ............. 16
1.4 F irm AI adoption rate across OECD countries, 2024  ......................... 18
1.5 T he 4 Cs of AI foundations ............................................. 20
2.1 M obile network coverage, by country income group, 2022 and 2024  ............ 27
2.2 G rowth in commercial communications satellite constellations, by orbital
positioning, 2015–23 ................................................. 28
2.3 I CT goods exports, 2022–23  ........................................... 29
2.4 G rowth of IT services exports, by country income group, 2022–23  ............. 31
2.5 I nternet penetration, globally and by income group, 2022 versus 2024  ........... 32
2.6 F ixed and mobile broadband penetration, globally and by income group,
2022 and 2024 ...................................................... 33
2.7 M edian fixed and mobile download speed, by country income group,
2023 and 2024 ...................................................... 34
2.8 W ithin-country internet speed inequality, 2019 Q1 and 2024 Q4  ............... 35
2.9 M edian fixed and mobile broadband traffic, by country income group,
2022 and 2023 ...................................................... 36
3.1 A I compute market segments and key companies  ............................ 41
3.2 C ompute capacity, by country income group and region  ...................... 45
3.3 U S cloud computing exports, by destination country income group and
region, 2019–23 ..................................................... 47
4.1 P roduction chain for training data  ....................................... 59
4.2 T raining AI in a data desert: VC investments in training data, by country
and region ......................................................... 61
4.3 P redominance of English in online content  ................................. 63
5.1 C lassification of digital skills  ............................................ 73
5.2 E xposure to digitization through the use of technologies and IT tools,
by occupation, 2015 and 2024 .......................................... 74
5.3 T rends in AI and GenAI skills demand across country income groups, 2021–24  .... 78
5.4 T op occupations requiring GenAI skills, 2024  .............................. 80
5.5 S upply of digital skills, 2023  ............................................ 82
5.6 S hare of workers with AI and GenAI skills, by educational attainment, 2024  ...... 84
5.7 T op occupations in which workers are most likely to have GenAI skills, 2024  ..... 85
5.8 C ross-border migration of high-skilled talent, 2022  .......................... 86
6.1 C ountry AI readiness level, 2024  ........................................ 95
A.1 T hematic case studies: AI and the three pillars  ............................. 102
viii  DIGITAL PROGRESS AND TRENDS REPORT 2025
Map
1.1 C hatGPT traffic, by country, 2024  ........................................ 15
Table
6.1 P rioritize AI investments on the basis of AI readiness  ......................... 93
  ix
Foreword
Artificial intelligence (AI) is advancing at an extraordinary speed, reshaping how people learn,
work, and live. Its ability to unlock access to knowledge, boost productivity, and open new markets
holds immense potential to accelerate development—creating jobs, new industries, and economic
transformation.
Expanding digital access will be one of the greatest drivers of future employment: 10 of the 15 fastest
growing jobs globally are now in technology or technology-enabled roles. In addition, AI-related
job postings are now rising faster in middle-income economies—up 16 percent in upper-middle-
income and 11 percent in lower-middle-income countries—compared to just 2 percent in high-income
countries.
This report, Strengthening AI Foundations, is the second in the Digital Progress and Trends Report
series, providing a comprehensive, data-driven snapshot of the global AI landscape. It highlights a
stark divide: Most innovations remain concentrated in high-income countries. Yet, a promising trend
is emerging, as low- and middle-income countries are actively adopting “small AI” solutions. While
these immediate, localized impacts are crucial, continued investment in strengthening the broader AI
foundations is needed to embrace AI at scale over time.
To seize this opportunity and facilitate the growth of small AI, governments need to prioritize
investment in what we call the foundational “4Cs”:
• Connectivity,  encompassing reliable digital infrastructure, energy, and device access, is the
indispensable baseline.
• Compute, covering AI chips, servers, data centers, and cloud services, is increasingly becoming the
“new electricity” of the AI era.
• Context, or locally relevant data and content, is essential to build trusted, inclusive, and effective
AI systems.
• Competency is the set of robust digital skills that are indispensable for adopting, adapting, and
innovating with AI.
Governments have a pivotal role to play in building and strengthening these critical foundations so
that AI can take root and flourish in developing countries. The World Bank Group is committed to
helping countries harness AI for inclusive and sustainable development, including supporting the 4Cs,
strengthening data governance, championing regulatory and institutional reforms, and investing in
the human capital essential to thrive in today’s digital era.
x  DIGITAL PROGRESS AND TRENDS REPORT 2025
Our new World Bank Group digital strategy includes AI readiness as a core pillar. It also emphasizes
the importance of having dynamic local innovation ecosystems and ensuring that AI tools are aligned
with local realities and priorities. Policies that promote competition and equitable distribution of AI
gains will be critical for mitigating risks and ensuring broad-based benefits.
As the AI era accelerates, developing countries need to be prepared to leap forward. Small AI offers a
unique opportunity to bypass traditional development barriers and spark homegrown innovation and
inclusive growth.
This report is a call for collective and strategic action. To ensure that AI becomes a force for shared
prosperity—rather than a new source of inequality—we must work together to expand access, close
skill gaps, manage risks, and shape a future where the transformative power of AI truly benefits
everyone.
Axel van Trotsenburg
Senior Managing Director
World Bank
  xi
Acknowledgments
The Digital Progress and Trends Report 2025 was prepared by a World Bank team led by Yan Liu,
under the guidance of Christine Zhenwei Qiang, Global Director for Digital Foundations. The core
team consisted of Yan Liu, Antonio Martins Neto, Sharada Srinivasan, Saloni Khurana, He Wang,
and Juan Porras. Key inputs were received from Hans Christian Boy, Nnamdi Itefchi-Fred, Ozzeir
Nisar Khan, Roman Kovalenko, and Oleg V. Petrov.
• The overview was authored by Christine Zhenwei Qiang and Yan Liu (refer to https://hdl.handle
.net/10986/43822).
• Chapter 1 was authored by Yan Liu and Sharada Srinivasan, with input from Oleg V. Petrov,
Ozzeir Nisar Khan, and Roman Kovalenko.
• Chapter 2 was authored by Saloni Khurana, with input from Antonio Martins Neto and Nnamdi
Itefchi-Fred.
• Chapter 3 was authored by Yan Liu, with input from Hans Christian Boy.
• Chapter 4 was authored by He Wang, with input from Yan Liu.
• Chapter 5 was authored by Saloni Khurana, Yan Liu, and Juan Porras.
• Chapter 6 was authored by Yan Liu.
• Appendix A was authored by Antonio Martins Neto.
• Case Study 1, “Exploring AI’s Disruptive Promise for Education Systems in Low- and Middle-
Income Countries,” was authored by Sharada Srinivasan and Alex Twinomugisha (refer to https://
hdl .handle.net/10986/43822).
• Case Study 2, “Harnessing AI for Efficiency: Transforming Agriculture and Energy Sectors,” was
authored by Antonio Martins Neto (refer to https://hdl.handle.net/10986/43822).
• Case Study 3, “Co-worker, Coach, or Competitor? How AI Is Transforming Digitally Deliverable
Services,” was authored by Johan Bjurman Bergman and He Wang (refer to https://hdl.handle
.net/10986/43822).
The team is grateful to the many reviewers who provided thoughtful insights and guidance at various
stages of the report’s preparation. Anton Korinek, Professor in the Department of Economics and
Darden School of Business, University of Virginia, served as the external peer reviewer. Internal
peer reviewers included Gabriel Demombynes, Tim Kelly, Auguste Tano Kouame, Aart Kraay,
Gaurav Nayyar, Michel Rogy, Stephane Straub, Davide Strusani, and Marie-Chantal Uwanyiligira.
Additional written comments were received from Doerte Doemeland, Amy Jean Doherty, Elisabeth
Huybens, Martin Raiser, David Satola, and Renaud Seligmann, as well as from the People Vice
Presidency.
xii  DIGITAL PROGRESS AND TRENDS REPORT 2025
The team particularly appreciates the guidance and support of Axel van Trotsenburg, Indermit Gill,
Sangbu Kim, Christine Zhenwei Qiang, Stephane Straub, and Ozan Sevimili.
Special thanks are due to Kelly Suzanne Alderson, Sharmista Appaya, Andrea Barone, Johan Bjurman
Bergman, Breen Byrnes, Peter Kusek, Monica Yanez Pagans, Camila Saad, Ghislain de Salins,
Clara Stinshoff, Casey Torgusson, and Christopher Tullis for their helpful comments and suggestions.
The team also appreciates contributions from colleagues across Verticals and the International Finance
Corporation (IFC) during workshops with IFC and the Agriculture, Education, Energy, and Finance,
Competitiveness, and Innovation Global Departments on the sectoral case studies.
The team thanks the following organizations for participating in various stakeholder consultations
and providing valuable inputs: Meta, Microsoft, and Peking University.
The report was funded by the World Bank and the Digital Development Partnership 2.0 Trust Fund,
a World Bank initiative supported by development partners aiming to advance digital transformation
in low- and middle-income countries by building strong digital foundations and enablers while
facilitating use cases for digital economies to thrive.

In [9]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter_2 = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100
)

chunks_2 = text_splitter_2.split_text(text)

print("Number of chunks:", len(chunks_2))
print("\nFirst chunk:\n")
print(chunks_2[0])

Number of chunks: 429

First chunk:

DIGITAL PROGRESS AND TRENDS REPORT 2025
STRENGTHENING
AI FOUNDATIONS
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Digital Progress and
Trends Report 2025
This book, along with any associated content or subsequent updates,
can be accessed at https://hdl.handle.net/10986/43822.
Scan to see all titles in this collection.
Digital Progress and
Trends Report 2025
Strengthening AI Foundations
© 2025 International Bank for Reconstruction and Development / The World Bank
1818 H Street NW, Washington, DC 20433
Telephone: 202-473-1000; Internet: www.worldbank.org
Some rights reserved
1 2 3 4  28 27 26 25
This work is a product of the staff of The World Bank with external contributions. The findings, interpretations, and
conclusions expressed in this work do not necessarily reflect the views of The World Bank, its Board of Executive Directors,
or the governments they represent.

In [10]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully!

In [11]:
embeddings = embedding_model.encode(
    chunks_2,
    show_progress_bar=True
)

print("Number of embeddings:", len(embeddings))
print("Embedding size:", embeddings.shape[1])

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

Number of embeddings: 429
Embedding size: 384

In [12]:
import faiss
import numpy as np

embeddings = np.array(embeddings).astype("float32")

index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(embeddings)

print("FAISS index created!")
print("Vectors stored:", index.ntotal)

FAISS index created!
Vectors stored: 429

In [13]:
def retrieve_chunks(question, k=3):
    question_embedding = embedding_model.encode([question])
    question_embedding = np.array(question_embedding).astype("float32")

    distances, indices = index.search(question_embedding, k)

    results = []

    for i, distance in zip(indices[0], distances[0]):
        results.append({
            "chunk": chunks_2[i],
            "distance": float(distance)
        })

    return results

In [14]:
question = "What is artificial intelligence?"

results = retrieve_chunks(question, k=3)

for i, result in enumerate(results, 1):
    print(f"\n--- Source {i} ---")
    print(result["chunk"])
    print("Distance:", result["distance"])

--- Source 1 ---
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once
exclusive to humans are now within the purview of machines. As a result, experts in the field often
joke that AI is everything that computers cannot currently do. AI also has become a marketing
buzzword, with companies rushing to label products as being AI based to ride the hype. Hence, it is
challenging to provide a precise definition of AI or even of its types or subfields.
This publication defines AI broadly, encompassing subfields such as predictive AI based on machine
Distance: 0.7693901062011719

--- Source 2 ---
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all
sorts of tasks by delegating them to other software and even people. Traditional AI requires
human input to navigate complex scenarios or shifting priorities. Agentic AI autonomously sets
subgoals, resolves conflicts, and adjusts its strategies using real-time feedback—often anticipating
needs before they arise. Agentic AI can handle complex, multistep reasoning, orchestrate entire
workflows, negotiate trade-offs, and integrate cross-domain knowledge to achieve higher-order
Distance: 0.8466377854347229

--- Source 3 ---
/42500). AI = artificial intelligence.
 H ARNESSING  AI  f OR  D E v ELOPMENT :  C AN  I T  W OR k?   21
• Compute refers to the availability and affordability of processing power, such as AI chips, data
centers, and cloud computing, which are necessary to train and deploy models at scale.
• Context encompasses the training data, models, and applications tailored to local languages,
cultures, needs, and governance frameworks, without which AI tools may remain irrelevant or
untrusted.
• Competency captures the digital skills and broader capabilities required to integrate AI into
workflows and build new solutions.
Although all four components are necessary across the board, their relative importance and
required sophistication differ depending on whether a country is focused on adoption, adaptation,
or innovation. For basic adoption of off-the-shelf AI tools, countries must prioritize widespread
Distance: 0.8887308835983276

In [16]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=150
)

print("Answer model loaded!")

model.safetensors: reconstructing file:   0%|          |  0.00B /  990MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] The model 'T5ForConditionalGeneration' is not supported for text-generation. Supported models are ['PeftModelForCausalLM', 'AfmoeForCausalLM', 'ApertusForCausalLM', 'ArceeForCausalLM', 'AriaTextForCausalLM', 'AXK1ForCausalLM', 'AXK2ForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BitNetForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'BltForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'Cohere2MoeForCausalLM', 'CohereCompassForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'CwmForCausalLM', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'DeepseekV32ForCausalLM', 'DeepseekV4ForCausalLM', 'DiffLlamaForCausalLM', 'DogeForCausalLM', 'Dots1ForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'Ernie4_5ForCausalLM', 'Ernie4_5_MoeForCausalLM', 'Exaone4ForCausalLM', 'ExaoneMoeForCausalLM', 'FalconForCausalLM', 'FalconH1ForCausalLM', 'FalconMambaForCausalLM', 'FlexOlmoForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma3ForConditionalGeneration', 'Gemma3ForCausalLM', 'Gemma3nForConditionalGeneration', 'Gemma3nForCausalLM', 'Gemma4ForConditionalGeneration', 'Gemma4AssistantForCausalLM', 'Gemma4ForCausalLM', 'Gemma4UnifiedForConditionalGeneration', 'Gemma4UnifiedAssistantForCausalLM', 'Gemma4UnifiedForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'Glm4ForCausalLM', 'Glm4MoeForCausalLM', 'Glm4MoeLiteForCausalLM', 'GlmMoeDsaForCausalLM', 'GotOcr2ForConditionalGeneration', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GptOssForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteSWAForCausalLM', 'GraniteMoeForCausalLM', 'GraniteMoeSWAForCausalLM', 'GraniteMoeHybridForCausalLM', 'GraniteMoeSharedForCausalLM', 'HeliumForCausalLM', 'HrmTextForCausalLM', 'HunYuanDenseV1ForCausalLM', 'HunYuanMoEV1ForCausalLM', 'HYV3ForCausalLM', 'HyperCLOVAXForCausalLM', 'InklingForCausalLM', 'Jais2ForCausalLM', 'JambaForCausalLM', 'JetMoeForCausalLM', 'LagunaForCausalLM', 'Lfm2ForCausalLM', 'Lfm2MoeForCausalLM', 'LlamaForCausalLM', 'Llama4ForCausalLM', 'Llama4ForCausalLM', 'LongcatFlashForCausalLM', 'MambaForCausalLM', 'Mamba2ForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegatronBertForCausalLM', 'MellumForCausalLM', 'MiMoV2FlashForCausalLM', 'MiniCPM3ForCausalLM', 'MiniMaxForCausalLM', 'MiniMaxM2ForCausalLM', 'MiniMaxM3VLForCausalLM', 'MinistralForCausalLM', 'Ministral3ForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MllamaForCausalLM', 'ModernBertDecoderForCausalLM', 'MoshiForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MusicgenMelodyForCausalLM', 'MvpForCausalLM', 'NanoChatForCausalLM', 'NemotronForCausalLM', 'NemotronHForCausalLM', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'Olmo3ForCausalLM', 'OlmoHybridForCausalLM', 'OlmoeForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi4MultimodalForCausalLM', 'PhimoeForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'Qwen3ForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3MoeForCausalLM', 'Qwen3NextForCausalLM', 'Qwen4ExpForCausalLM', 'Qwen4ExpForCausalLM', 'RecurrentGemmaForCausalLM', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'SeedOssForCausalLM', 'SmolLM3ForCausalLM', 'SolarOpenForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'TrOCRForCausalLM', 'VaultGemmaForCausalLM', 'WhisperForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'xLSTMForCausalLM', 'XmodForCausalLM', 'YoutuForCausalLM', 'ZambaForCausalLM', 'Zamba2ForCausalLM', 'ZayaForCausalLM'].

Answer model loaded!

In [17]:
def answer_question(question, k=3):
    results = retrieve_chunks(question, k)

    context = "\n\n".join([r["chunk"] for r in results])

    prompt = f"""
Answer the question using only the context below.

If the answer cannot be found in the context, say exactly:
I don't know

Context:
{context}

Question:
{question}

Answer:
"""

    response = generator(prompt)[0]["generated_text"]

    print("ANSWER:")
    print(response)

    print("\nSOURCES:")
    for i, result in enumerate(results, 1):
        print(f"\n--- Source {i} ---")
        print(result["chunk"][:500])

In [18]:
answer_question("What is artificial intelligence?")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (611 > 512). Running this sequence through the model will result in indexing errors
[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:

Answer the question using only the context below.

If the answer cannot be found in the context, say exactly:
I don't know

Context:
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once
exclusive to humans are now within the purview of machines. As a result, experts in the field often
joke that AI is everything that computers cannot currently do. AI also has become a marketing
buzzword, with companies rushing to label products as being AI based to ride the hype. Hence, it is
challenging to provide a precise definition of AI or even of its types or subfields.
This publication defines AI broadly, encompassing subfields such as predictive AI based on machine

logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all
sorts of tasks by delegating them to other software and even people. Traditional AI requires
human input to navigate complex scenarios or shifting priorities. Agentic AI autonomously sets
subgoals, resolves conflicts, and adjusts its strategies using real-time feedback—often anticipating
needs before they arise. Agentic AI can handle complex, multistep reasoning, orchestrate entire
workflows, negotiate trade-offs, and integrate cross-domain knowledge to achieve higher-order

/42500). AI = artificial intelligence.
 H ARNESSING  AI  f OR  D E v ELOPMENT :  C AN  I T  W OR k?   21
• Compute refers to the availability and affordability of processing power, such as AI chips, data
centers, and cloud computing, which are necessary to train and deploy models at scale.
• Context encompasses the training data, models, and applications tailored to local languages,
cultures, needs, and governance frameworks, without which AI tools may remain irrelevant or
untrusted.
• Competency captures the digital skills and broader capabilities required to integrate AI into
workflows and build new solutions.
Although all four components are necessary across the board, their relative importance and
required sophistication differ depending on whether a country is focused on adoption, adaptation,
or innovation. For basic adoption of off-the-shelf AI tools, countries must prioritize widespread

Question:
What is artificial intelligence?

Answer:


SOURCES:

--- Source 1 ---
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once
exclusive to humans are now within the

--- Source 2 ---
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all
sorts of tasks by delegating them to other

--- Source 3 ---
/42500). AI = artificial intelligence.
 H ARNESSING  AI  f OR  D E v ELOPMENT :  C AN  I T  W OR k?   21
• Compute refers to the availability and affordability of processing power, such as AI chips, data
centers, and cloud computing, which are necessary to train and deploy models at scale.
• Context encompasses the training data, models, and applications tailored to local languages,
cultures, needs, and governance frameworks, without which AI tools may remain irrelevant or
untrusted.
• Compe

In [19]:
def answer_question(question, k=3, threshold=1.5):
    results = retrieve_chunks(question, k)

    # Check whether the retrieved chunks are relevant
    best_distance = results[0]["distance"]

    if best_distance > threshold:
        print("ANSWER:")
        print("I don't know")
        print("\nNo sufficiently relevant information was found in the document.")
        return

    context = "\n\n".join([r["chunk"] for r in results])

    prompt = f"""
Answer the question using ONLY the context below.

If the answer is not present in the context, say exactly:
I don't know

Context:
{context}

Question:
{question}

Answer:
"""

    response = generator(prompt)[0]["generated_text"]

    print("ANSWER:")
    print(response)

    print("\nSOURCES:")
    for i, result in enumerate(results, 1):
        print(f"\n--- Source {i} ---")
        print(result["chunk"][:500])

In [20]:
answer_question("What is artificial intelligence?")

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:

Answer the question using ONLY the context below.

If the answer is not present in the context, say exactly:
I don't know

Context:
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once
exclusive to humans are now within the purview of machines. As a result, experts in the field often
joke that AI is everything that computers cannot currently do. AI also has become a marketing
buzzword, with companies rushing to label products as being AI based to ride the hype. Hence, it is
challenging to provide a precise definition of AI or even of its types or subfields.
This publication defines AI broadly, encompassing subfields such as predictive AI based on machine

logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all
sorts of tasks by delegating them to other software and even people. Traditional AI requires
human input to navigate complex scenarios or shifting priorities. Agentic AI autonomously sets
subgoals, resolves conflicts, and adjusts its strategies using real-time feedback—often anticipating
needs before they arise. Agentic AI can handle complex, multistep reasoning, orchestrate entire
workflows, negotiate trade-offs, and integrate cross-domain knowledge to achieve higher-order

/42500). AI = artificial intelligence.
 H ARNESSING  AI  f OR  D E v ELOPMENT :  C AN  I T  W OR k?   21
• Compute refers to the availability and affordability of processing power, such as AI chips, data
centers, and cloud computing, which are necessary to train and deploy models at scale.
• Context encompasses the training data, models, and applications tailored to local languages,
cultures, needs, and governance frameworks, without which AI tools may remain irrelevant or
untrusted.
• Competency captures the digital skills and broader capabilities required to integrate AI into
workflows and build new solutions.
Although all four components are necessary across the board, their relative importance and
required sophistication differ depending on whether a country is focused on adoption, adaptation,
or innovation. For basic adoption of off-the-shelf AI tools, countries must prioritize widespread

Question:
What is artificial intelligence?

Answer:


SOURCES:

--- Source 1 ---
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once
exclusive to humans are now within the

--- Source 2 ---
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all
sorts of tasks by delegating them to other

--- Source 3 ---
/42500). AI = artificial intelligence.
 H ARNESSING  AI  f OR  D E v ELOPMENT :  C AN  I T  W OR k?   21
• Compute refers to the availability and affordability of processing power, such as AI chips, data
centers, and cloud computing, which are necessary to train and deploy models at scale.
• Context encompasses the training data, models, and applications tailored to local languages,
cultures, needs, and governance frameworks, without which AI tools may remain irrelevant or
untrusted.
• Compe

In [21]:
answer_question("What is the recipe for making pizza?")

ANSWER:
I don't know

No sufficiently relevant information was found in the document.

In [22]:
def answer_question_with_sources(question, k=3, threshold=1.5):
    results = retrieve_chunks(question, k)

    best_distance = results[0]["distance"]

    if best_distance > threshold:
        print("ANSWER:")
        print("I don't know")
        print("\nNo sufficiently relevant information was found in the document.")
        return

    context = "\n\n".join([r["chunk"] for r in results])

    prompt = f"""
Answer the question using ONLY the context below.
If the answer is not present in the context, say exactly: I don't know

Context:
{context}

Question:
{question}

Answer:
"""

    response = generator(prompt)[0]["generated_text"]

    print("=" * 60)
    print("ANSWER")
    print("=" * 60)
    print(response)

    print("\n" + "=" * 60)
    print("CITATIONS / SOURCE PASSAGES")
    print("=" * 60)

    for i, result in enumerate(results, 1):
        print(f"\n[Source {i}]")
        print(result["chunk"][:700])

In [23]:
answer_question_with_sources(
    "What are some important developments in artificial intelligence?"
)

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

============================================================
ANSWER
============================================================

Answer the question using ONLY the context below.
If the answer is not present in the context, say exactly: I don't know

Context:
AI development tools
GitHub Copilot (Microsoft),
Hugging Face, PyTorch (Meta),
TensorFlow (Google)
Traditional AI
algorithms and models
Alphabet, Apple, Meta,
TikTok, Tesla
Generative AI models
Alphabet, Anthropic, DeepSeek,
Mistral AI, Meta, Microsoft,
OpenAI
AI application
AI application software
Adobe, Grammarly, Harvey, Microsoft, OpenAI,
Stability AI, Jasper.ai, Soul Machines
AI-powered devices and equipment
Boston Dynamics, Intuitive Surgical, iRobot,
Tesla, Samsung, Waymo, Xiaomi
Source: Original figure for this publication.
Note: AI = artificial intelligence.
4  DIGITAL PROGRESS AND TRENDS REPORT 2025
Training data are yet another critical part of this ecosystem, which can be gathered from various
sources such as digital devices, sensors, digital platforms, business transactions, and public data sets.
These data are then aggregated into central repositories, labeled, and annotated. Data preprocessing

2024. https://www.wsj.com/tech/ai/yann-lecun-ai-meta-aa59e2f5.
Mirzadeh, I., K. Alizadeh, H. Shahrokhi, O. Tuzel, S. Bengio, and M. Farajtabar. 2024. “GSM-Symbolic:
Understanding the Limitations of Mathematical Reasoning in Large Language Models.” Preprint, last
revised August 27, 2025. https://arxiv.org/abs/2410.05229.
Narayanan, A., and S. Kapoor. 2024. AI Snake Oil: What Artificial Intelligence Can Do, What It Can’t,
and How to Tell the Difference. Princeton, NJ: Princeton University Press.
Narayanan, A., and S. Kapoor. 2025. AI as Normal Technology. New York: Knight First Amendment
Institute, Columbia University, New York. https://knightcolumbia.org/content/ai-as-normal -technology.
Noy, S., and W. Zhang. 2023. “Experimental Evidence on the Productivity Effects of Generative Artificial
Intelligence.” Science 381 (6654): 187–92.
OECD (Organisation for Economic Co-operation and Development). 2024. The Digital Economy

and poor economies may widen further.
Uneven progress in AI innovation, adaptation, and adoption
This report defines AI innovation, adaptation, and adoption as follows:
• AI innovation: The creation of new AI technologies, models, training data, or methodologies
that advance the state of the art.  This includes publishing fundamental research (for example,
in scientific publications), developing and launching notable AI models, patenting novel AI
techniques, commercializing original AI products, and forming AI-focused start-ups.
• AI adaptation: The modification or customization of existing AI technologies for specific
contexts, sectors, or applications.  Examples include building industry- or domain-specific
12  DIGITAL PROGRESS AND TRENDS REPORT 2025
AI tools on top of general-purpose models (for example, services built using the ChatGPT
application programming interface), fine-tuning open-source AI models for local languages or

Question:
What are some important developments in artificial intelligence?

Answer:


============================================================
CITATIONS / SOURCE PASSAGES
============================================================

[Source 1]
AI development tools
GitHub Copilot (Microsoft),
Hugging Face, PyTorch (Meta),
TensorFlow (Google)
Traditional AI
algorithms and models
Alphabet, Apple, Meta,
TikTok, Tesla
Generative AI models
Alphabet, Anthropic, DeepSeek,
Mistral AI, Meta, Microsoft,
OpenAI
AI application
AI application software
Adobe, Grammarly, Harvey, Microsoft, OpenAI,
Stability AI, Jasper.ai, Soul Machines
AI-powered devices and equipment
Boston Dynamics, Intuitive Surgical, iRobot,
Tesla, Samsung, Waymo, Xiaomi
Source: Original figure for this publication.
Note: AI = artificial intelligence.
4  DIGITAL PROGRESS AND TRENDS REPORT 2025
Training data are yet another critical part of this ecosystem, which c

[Source 2]
2024. https://www.wsj.com/tech/ai/yann-lecun-ai-meta-aa59e2f5.
Mirzadeh, I., K. Alizadeh, H. Shahrokhi, O. Tuzel, S. Bengio, and M. Farajtabar. 2024. “GSM-Symbolic:
Understanding the Limitations of Mathematical Reasoning in Large Language Models.” Preprint, last
revised August 27, 2025. https://arxiv.org/abs/2410.05229.
Narayanan, A., and S. Kapoor. 2024. AI Snake Oil: What Artificial Intelligence Can Do, What It Can’t,
and How to Tell the Difference. Princeton, NJ: Princeton University Press.
Narayanan, A., and S. Kapoor. 2025. AI as Normal Technology. New York: Knight First Amendment
Institute, Columbia University, New York. https://knightcolumbia.org/content/ai-as-normal -technology.


[Source 3]
and poor economies may widen further.
Uneven progress in AI innovation, adaptation, and adoption
This report defines AI innovation, adaptation, and adoption as follows:
• AI innovation: The creation of new AI technologies, models, training data, or methodologies
that advance the state of the art.  This includes publishing fundamental research (for example,
in scientific publications), developing and launching notable AI models, patenting novel AI
techniques, commercializing original AI products, and forming AI-focused start-ups.
• AI adaptation: The modification or customization of existing AI technologies for specific
contexts, sectors, or applications.  Examples include building indust

In [24]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

page_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100
)

page_chunks = []
page_numbers = []

for page_num, page in enumerate(reader.pages, start=1):
    page_text = page.extract_text()

    if page_text:
        chunks = page_splitter.split_text(page_text)

        for chunk in chunks:
            page_chunks.append(chunk)
            page_numbers.append(page_num)

print("Total chunks:", len(page_chunks))
print("Total page references:", len(page_numbers))

Total chunks: 488
Total page references: 488

In [25]:
page_embeddings = embedding_model.encode(
    page_chunks,
    show_progress_bar=True
)

page_embeddings = np.array(page_embeddings).astype("float32")

page_index = faiss.IndexFlatL2(page_embeddings.shape[1])
page_index.add(page_embeddings)

print("FAISS index created!")
print("Vectors stored:", page_index.ntotal)

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

FAISS index created!
Vectors stored: 488

In [27]:
def retrieve_page_chunks(question, k=3):
    question_embedding = embedding_model.encode([question])
    question_embedding = np.array(question_embedding).astype("float32")

    distances, indices = page_index.search(question_embedding, k)

    results = []

    for i, distance in zip(indices[0], distances[0]):
        results.append({
            "chunk": page_chunks[i],
            "distance": float(distance),
            "page": page_numbers[i]
        })

    return results

results = retrieve_page_chunks(
    "What is artificial intelligence?",
    k=3
)

for i, result in enumerate(results, 1):
    print(f"\n--- Source {i} | Page {result['page']} ---")
    print(result["chunk"][:500])

--- Source 1 | Page 24 ---
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require

--- Source 2 | Page 28 ---
a degree of autonomy, making decisions based on the data they have learned from and tackling
more complex cognitive problems. This autonomy in optimization and decision-making allows
AI to either substitute for or complement human decision-making and judgment.
2. Data dependency. AI relies heavily on large data sets for training and operation. This contrasts
with technologies such as the steam engine, electricity, internal combustion engine,
telecommunications, computers, and the internet, w

--- Source 3 | Page 26 ---
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that re

In [28]:
def answer_with_page_citations(question, k=3, threshold=1.5):
    results = retrieve_page_chunks(question, k)

    # Check relevance
    if not results or results[0]["distance"] > threshold:
        print("ANSWER:")
        print("I don't know")
        print("\nNo sufficiently relevant information was found in the document.")
        return

    context = "\n\n".join(
        [f"[Page {r['page']}]\n{r['chunk']}" for r in results]
    )

    prompt = f"""
Answer the question using ONLY the context below.

If the answer is not present in the context, say exactly:
I don't know

Context:
{context}

Question:
{question}

Answer:
"""

    response = generator(prompt)[0]["generated_text"]

    print("=" * 60)
    print("ANSWER")
    print("=" * 60)
    print(response)

    print("\n" + "=" * 60)
    print("CITATIONS")
    print("=" * 60)

    for i, result in enumerate(results, 1):
        print(f"\n[Source {i} | Page {result['page']}]")
        print(result["chunk"][:700])

In [29]:
answer_with_page_citations(
    "What is artificial intelligence?"
)

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

============================================================
ANSWER
============================================================

Answer the question using ONLY the context below.

If the answer is not present in the context, say exactly:
I don't know

Context:
[Page 24]
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once

[Page 28]
a degree of autonomy, making decisions based on the data they have learned from and tackling
more complex cognitive problems. This autonomy in optimization and decision-making allows
AI to either substitute for or complement human decision-making and judgment.
2. Data dependency. AI relies heavily on large data sets for training and operation. This contrasts
with technologies such as the steam engine, electricity, internal combustion engine,
telecommunications, computers, and the internet, which require infrastructure but not vast data
inputs. Computers, the internet, social media, and digital platforms all use and generate data,
but they can operate without much data. They also primarily process or transmit data according
to predefined rules. They do not learn and adapt in the same way AI does.
GenAI further differs from previous AI in the following aspects:
• Prediction with unstructured data, enabling content generation;

[Page 26]
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all

Question:
What is artificial intelligence?

Answer:


============================================================
CITATIONS
============================================================

[Source 1 | Page 24]
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more pow

[Source 2 | Page 28]
a degree of autonomy, making decisions based on the data they have learned from and tackling
more complex cognitive problems. This autonomy in optimization and decision-making allows
AI to either substitute for or complement human decision-making and judgment.
2. Data dependency. AI relies heavily on large data sets for training and operation. This contrasts
with technologies such as the steam engine, electricity, internal combustion engine,
telecommunications, computers, and the internet, which require infrastructure but not vast data
inputs. Computers, the internet, social media, and digital platforms all use and generate data,
but they can operate without much data. They also primar

[Source 3 | Page 26]
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex p

In [30]:
answer_with_page_citations(
    "What are the main applications of artificial intelligence?"
)

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

============================================================
ANSWER
============================================================

Answer the question using ONLY the context below.

If the answer is not present in the context, say exactly:
I don't know

Context:
[Page 26]
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all

[Page 24]
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once

[Page 32]
for white-collar workers using GenAI, especially for less productive or lower-performing workers
(Brynjolfsson, Li, and Raymond 2025; Dell’Acqua et al. 2023; Noy and Zhang 2023).
However, current AI’s inherent flaws may limit its broader economic significance. First, the
hallucinations that GenAI tools produce are rooted in the mathematical and logical structure of
LLMs (Banerjee, Agarwal, and Singla 2024), making them unreliable in business environments
where mistakes can be costly. Second, current AI tools remain pattern recognition engines without
true understanding, common sense, or logical reasoning (Mirzadeh et al. 2024). Third, much
economically valuable knowledge is tacit, context specific, and difficult to codify in a form that AI
can learn from (Narayanan and Kapoor 2025).
AI will become more useful when it can “understand” and interact with the physical world. At
present, AI models are used mainly to optimize software and generate information, text, and images,

Question:
What are the main applications of artificial intelligence?

Answer:


============================================================
CITATIONS
============================================================

[Source 1 | Page 26]
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex p

[Source 2 | Page 24]
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more pow

[Source 3 | Page 32]
for white-collar workers using GenAI, especially for less productive or lower-performing workers
(Brynjolfsson, Li, and Raymond 2025; Dell’Acqua et al. 2023; Noy and Zhang 2023).
However, current AI’s inherent flaws may limit its broader economic significance. First, the
hallucinations that GenAI tools produce are rooted in the mathematical and logical structure of
LLMs (Banerjee, Agarwal, and Singla 2024), making them unreliable in business environments
where mistakes can be costly. Second, current AI tools remain pattern recognition engines without
true understanding, common sense, or logical reasoning (Mirzadeh et al. 2024). Third, much
economically valuable knowledge is tacit, cont

In [31]:
answer_with_page_citations(
    "What are some challenges associated with artificial intelligence?"
)

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

============================================================
ANSWER
============================================================

Answer the question using ONLY the context below.

If the answer is not present in the context, say exactly:
I don't know

Context:
[Page 45]
2024. https://www.wsj.com/tech/ai/yann-lecun-ai-meta-aa59e2f5.
Mirzadeh, I., K. Alizadeh, H. Shahrokhi, O. Tuzel, S. Bengio, and M. Farajtabar. 2024. “GSM-Symbolic:
Understanding the Limitations of Mathematical Reasoning in Large Language Models.” Preprint, last
revised August 27, 2025. https://arxiv.org/abs/2410.05229.
Narayanan, A., and S. Kapoor. 2024. AI Snake Oil: What Artificial Intelligence Can Do, What It Can’t,
and How to Tell the Difference. Princeton, NJ: Princeton University Press.
Narayanan, A., and S. Kapoor. 2025. AI as Normal Technology. New York: Knight First Amendment
Institute, Columbia University, New York. https://knightcolumbia.org/content/ai-as-normal -technology.
Noy, S., and W. Zhang. 2023. “Experimental Evidence on the Productivity Effects of Generative Artificial
Intelligence.” Science 381 (6654): 187–92.
OECD (Organisation for Economic Co-operation and Development). 2024. The Digital Economy

[Page 26]
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all

[Page 42]
20  DIGITAL PROGRESS AND TRENDS REPORT 2025
this drain. These barriers collectively create a challenging environment for AI innovation, limiting
the ability of developing countries to contribute to and benefit from advancements in AI technology.
The adoption of AI technologies in developing countries is similarly hindered by a range of structural,
economic, and social challenges. Limited digital infrastructure, characterized by unreliable internet
connectivity and insufficient access to smart devices, forms a fundamental barrier to widespread
AI adoption. A significant skills gap in the workforce can make it difficult for organizations to
effectively implement and manage AI systems. Cultural and language barriers also play a crucial
role, because many AI systems are not adapted to local languages or cultural nuances, leading to
reduced effectiveness and acceptance.
Financial constraints pose another significant hurdle, with the high initial costs of AI implementation

Question:
What are some challenges associated with artificial intelligence?

Answer:


============================================================
CITATIONS
============================================================

[Source 1 | Page 45]
2024. https://www.wsj.com/tech/ai/yann-lecun-ai-meta-aa59e2f5.
Mirzadeh, I., K. Alizadeh, H. Shahrokhi, O. Tuzel, S. Bengio, and M. Farajtabar. 2024. “GSM-Symbolic:
Understanding the Limitations of Mathematical Reasoning in Large Language Models.” Preprint, last
revised August 27, 2025. https://arxiv.org/abs/2410.05229.
Narayanan, A., and S. Kapoor. 2024. AI Snake Oil: What Artificial Intelligence Can Do, What It Can’t,
and How to Tell the Difference. Princeton, NJ: Princeton University Press.
Narayanan, A., and S. Kapoor. 2025. AI as Normal Technology. New York: Knight First Amendment
Institute, Columbia University, New York. https://knightcolumbia.org/content/ai-as-normal -technology.


[Source 2 | Page 26]
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex p

[Source 3 | Page 42]
20  DIGITAL PROGRESS AND TRENDS REPORT 2025
this drain. These barriers collectively create a challenging environment for AI innovation, limiting
the ability of developing countries to contribute to and benefit from advancements in AI technology.
The adoption of AI technologies in developing countries is similarly hindered by a range of structural,
economic, and social challenges. Limited digital infrastructure, characterized by unreliable internet
connectivity and insufficient access to smart devices, forms a fundamental barrier to widespread
AI adoption. A significant skills gap in the workforce can make it difficult for organizations to
effectively implement and manage AI systems. C

In [32]:
answer_with_page_citations(
    "What is the capital city of Japan?"
)

ANSWER:
I don't know

No sufficiently relevant information was found in the document.

In [33]:
print("CHUNKING COMPARISON")
print("=" * 50)

print("\nStrategy 1: Fixed Character Chunking")
print("Number of chunks:", len(chunks_1))
print("Average chunk length:",
      sum(len(c) for c in chunks_1) / len(chunks_1))

print("\nStrategy 2: Recursive Character Chunking")
print("Number of chunks:", len(chunks_2))
print("Average chunk length:",
      sum(len(c) for c in chunks_2) / len(chunks_2))

CHUNKING COMPARISON
==================================================

Strategy 1: Fixed Character Chunking
Number of chunks: 1
Average chunk length: 381409.0

Strategy 2: Recursive Character Chunking
Number of chunks: 429
Average chunk length: 954.3799533799533

In [34]:
def retrieve_with_index(question, chunks, index, k=3):
    question_embedding = embedding_model.encode([question])
    question_embedding = np.array(question_embedding).astype("float32")

    distances, indices = index.search(question_embedding, k)

    return [
        {
            "chunk": chunks[i],
            "distance": float(distance)
        }
        for i, distance in zip(indices[0], distances[0])
    ]

In [35]:
embeddings_1 = embedding_model.encode(
    chunks_1,
    show_progress_bar=True
)

embeddings_1 = np.array(embeddings_1).astype("float32")

index_1 = faiss.IndexFlatL2(embeddings_1.shape[1])
index_1.add(embeddings_1)

print("Strategy 1 index:", index_1.ntotal)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Strategy 1 index: 1

In [36]:
questions = [
    "What is artificial intelligence?",
    "What are the challenges of artificial intelligence?",
    "How is AI being used in different sectors?"
]

for question in questions:
    results_1 = retrieve_with_index(
        question, chunks_1, index_1
    )

    results_2 = retrieve_with_index(
        question, chunks_2, index,
    )

    print("\n" + "=" * 70)
    print("QUESTION:", question)

    print("\nStrategy 1 - Best distance:",
          results_1[0]["distance"])

    print("Strategy 2 - Best distance:",
          results_2[0]["distance"])

======================================================================
QUESTION: What is artificial intelligence?

Strategy 1 - Best distance: 1.4968130588531494
Strategy 2 - Best distance: 0.7693901062011719

======================================================================
QUESTION: What are the challenges of artificial intelligence?

Strategy 1 - Best distance: 1.459427833557129
Strategy 2 - Best distance: 0.8886390924453735

======================================================================
QUESTION: How is AI being used in different sectors?

Strategy 1 - Best distance: 1.3863714933395386
Strategy 2 - Best distance: 0.7529107332229614

In [37]:
def compare_retrieval(question, k=3):
    results_1 = retrieve_with_index(
        question, chunks_1, index_1, k
    )

    results_2 = retrieve_with_index(
        question, chunks_2, index, k
    )

    print("=" * 70)
    print("QUESTION:", question)

    print("\n--- STRATEGY 1: FIXED-SIZE ---")
    for i, r in enumerate(results_1, 1):
        print(f"\nSource {i} | Distance: {r['distance']:.4f}")
        print(r["chunk"][:400])

    print("\n--- STRATEGY 2: RECURSIVE ---")
    for i, r in enumerate(results_2, 1):
        print(f"\nSource {i} | Distance: {r['distance']:.4f}")
        print(r["chunk"][:400])

In [38]:
compare_retrieval(
    "What are the main applications of artificial intelligence?"
)

======================================================================
QUESTION: What are the main applications of artificial intelligence?

--- STRATEGY 1: FIXED-SIZE ---

Source 1 | Distance: 1.5462
DIGITAL PROGRESS AND TRENDS REPORT 2025
STRENGTHENING
AI FOUNDATIONS
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Digital Progress and
Trends Report 2025
This book, along with any associated content or subsequent updates,
can be accessed at https://hdl.handle.net/10986/43822.
Scan to see all titles in this collection.
Digi

Source 2 | Distance: 340282346638528859811704183484516925440.0000
DIGITAL PROGRESS AND TRENDS REPORT 2025
STRENGTHENING
AI FOUNDATIONS
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Digital Progress and
Trends Report 2025
This book, along with any associated content or subsequent updates,
can be accessed at https://hdl.handle.net/10986/43822.
Scan to see all titles in this collection.
Digi

Source 3 | Distance: 340282346638528859811704183484516925440.0000
DIGITAL PROGRESS AND TRENDS REPORT 2025
STRENGTHENING
AI FOUNDATIONS
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Public Disclosure Authorized
Digital Progress and
Trends Report 2025
This book, along with any associated content or subsequent updates,
can be accessed at https://hdl.handle.net/10986/43822.
Scan to see all titles in this collection.
Digi

--- STRATEGY 2: RECURSIVE ---

Source 1 | Distance: 0.9058
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to

Source 2 | Distance: 0.9261
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and

Source 3 | Distance: 0.9306
◦ Intentional AI adoption by firms remains limited (8 percent) even in advanced economies,
and it is lower in developing countries.
• Promising use cases are emerging across developing countries and across sectors. Realizing
the potential of AI hinges on the foundational 4 Cs: connectivity, compute, context (training
data, models, and applications), and competency (digital skills).
 ◦ In Brazil

In [39]:
test_questions = [
    "What is artificial intelligence?",
    "What are the main applications of artificial intelligence?",
    "What are the challenges of artificial intelligence?",
    "How is AI used in different sectors?",
    "What are the foundations needed for AI?",
    "What factors affect AI adoption?"
]

for question in test_questions:
    print("\n" + "=" * 70)
    print("QUESTION:", question)

    r1 = retrieve_with_index(question, chunks_1, index_1, k=1)[0]
    r2 = retrieve_with_index(question, chunks_2, index, k=1)[0]

    print(f"Fixed-size distance: {r1['distance']:.4f}")
    print(f"Recursive distance:  {r2['distance']:.4f}")

======================================================================
QUESTION: What is artificial intelligence?
Fixed-size distance: 1.4968
Recursive distance:  0.7694

======================================================================
QUESTION: What are the main applications of artificial intelligence?
Fixed-size distance: 1.5462
Recursive distance:  0.9058

======================================================================
QUESTION: What are the challenges of artificial intelligence?
Fixed-size distance: 1.4594
Recursive distance:  0.8886

======================================================================
QUESTION: How is AI used in different sectors?
Fixed-size distance: 1.4107
Recursive distance:  0.7300

======================================================================
QUESTION: What are the foundations needed for AI?
Fixed-size distance: 1.2131
Recursive distance:  0.7497

======================================================================
QUESTION: What factors affect AI adoption?
Fixed-size distance: 1.4107
Recursive distance:  0.7528

In [40]:
import pandas as pd

comparison_results = []

for question in test_questions:
    r1 = retrieve_with_index(question, chunks_1, index_1, k=1)[0]
    r2 = retrieve_with_index(question, chunks_2, index, k=1)[0]

    comparison_results.append({
        "Question": question,
        "Fixed-size Distance": round(r1["distance"], 4),
        "Recursive Distance": round(r2["distance"], 4)
    })

comparison_df = pd.DataFrame(comparison_results)

comparison_df

,Question,Fixed-size Distance,Recursive Distance
0,What is artificial intelligence?,1.4968,0.7694
1,What are the main applications of artificial i...,1.5462,0.9058
2,What are the challenges of artificial intellig...,1.4594,0.8886
3,How is AI used in different sectors?,1.4107,0.7300
4,What are the foundations needed for AI?,1.2131,0.7497
5,What factors affect AI adoption?,1.4107,0.7528

In [41]:
print("Average Fixed-size Distance:",
      comparison_df["Fixed-size Distance"].mean())

print("Average Recursive Distance:",
      comparison_df["Recursive Distance"].mean())

Average Fixed-size Distance: 1.4228166666666666
Average Recursive Distance: 0.7993833333333332

In [42]:
evaluation_questions = [
    "What is artificial intelligence?",
    "What are the main applications of artificial intelligence?",
    "What are the challenges of artificial intelligence?",
    "How is AI used in different sectors?",
    "What are the foundations needed for AI?",
    "What factors affect AI adoption?"
]

for question in evaluation_questions:
    print("\n" + "=" * 80)
    print("QUESTION:", question)

    results = retrieve_page_chunks(question, k=2)

    for i, r in enumerate(results, 1):
        print(f"\nSOURCE {i} | PDF PAGE {r['page']}")
        print("-" * 60)
        print(r["chunk"][:1000])

================================================================================
QUESTION: What is artificial intelligence?

SOURCE 1 | PDF PAGE 24
------------------------------------------------------------
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once

SOURCE 2 | PDF PAGE 28
------------------------------------------------------------
a degree of autonomy, making decisions based on the data they have learned from and tackling
more complex cognitive problems. This autonomy in optimization and decision-making allows
AI to either substitute for or complement human decision-making and judgment.
2. Data dependency. AI relies heavily on large data sets for training and operation. This contrasts
with technologies such as the steam engine, electricity, internal combustion engine,
telecommunications, computers, and the internet, which require infrastructure but not vast data
inputs. Computers, the internet, social media, and digital platforms all use and generate data,
but they can operate without much data. They also primarily process or transmit data according
to predefined rules. They do not learn and adapt in the same way AI does.
GenAI further differs from previous AI in the following aspects:
• Prediction with unstructured data, enabling content generation;

================================================================================
QUESTION: What are the main applications of artificial intelligence?

SOURCE 1 | PDF PAGE 26
------------------------------------------------------------
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all

SOURCE 2 | PDF PAGE 24
------------------------------------------------------------
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once

================================================================================
QUESTION: What are the challenges of artificial intelligence?

SOURCE 1 | PDF PAGE 45
------------------------------------------------------------
2024. https://www.wsj.com/tech/ai/yann-lecun-ai-meta-aa59e2f5.
Mirzadeh, I., K. Alizadeh, H. Shahrokhi, O. Tuzel, S. Bengio, and M. Farajtabar. 2024. “GSM-Symbolic:
Understanding the Limitations of Mathematical Reasoning in Large Language Models.” Preprint, last
revised August 27, 2025. https://arxiv.org/abs/2410.05229.
Narayanan, A., and S. Kapoor. 2024. AI Snake Oil: What Artificial Intelligence Can Do, What It Can’t,
and How to Tell the Difference. Princeton, NJ: Princeton University Press.
Narayanan, A., and S. Kapoor. 2025. AI as Normal Technology. New York: Knight First Amendment
Institute, Columbia University, New York. https://knightcolumbia.org/content/ai-as-normal -technology.
Noy, S., and W. Zhang. 2023. “Experimental Evidence on the Productivity Effects of Generative Artificial
Intelligence.” Science 381 (6654): 187–92.
OECD (Organisation for Economic Co-operation and Development). 2024. The Digital Economy

SOURCE 2 | PDF PAGE 26
------------------------------------------------------------
watch a video, listen to the audio, read the subtitles, and generate a comprehensive summary of
what occurred. This allows for a much richer, more contextual understanding of the world and
enables more fluid and intuitive interactions with technology, moving it closer to how humans
perceive reality.
Beyond better perception, the field is intensely focused on advanced AI reasoning. Although current
models are excellent at pattern recognition, they can struggle with multistep problems that require
logical deduction, strategic planning, or creative problem-solving. The next frontier is to develop AI
that can not only retrieve information but can also reason with it to analyze a complex problem,
break it into smaller steps, form a coherent plan, and execute it. This capability is essential for
tackling grand challenges in science, medicine, and engineering.
Agentic AI  allows computers to go beyond chat and content generation and carry out all

================================================================================
QUESTION: How is AI used in different sectors?

SOURCE 1 | PDF PAGE 24
------------------------------------------------------------
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once

SOURCE 2 | PDF PAGE 32
------------------------------------------------------------
for white-collar workers using GenAI, especially for less productive or lower-performing workers
(Brynjolfsson, Li, and Raymond 2025; Dell’Acqua et al. 2023; Noy and Zhang 2023).
However, current AI’s inherent flaws may limit its broader economic significance. First, the
hallucinations that GenAI tools produce are rooted in the mathematical and logical structure of
LLMs (Banerjee, Agarwal, and Singla 2024), making them unreliable in business environments
where mistakes can be costly. Second, current AI tools remain pattern recognition engines without
true understanding, common sense, or logical reasoning (Mirzadeh et al. 2024). Third, much
economically valuable knowledge is tacit, context specific, and difficult to codify in a form that AI
can learn from (Narayanan and Kapoor 2025).
AI will become more useful when it can “understand” and interact with the physical world. At
present, AI models are used mainly to optimize software and generate information, text, and images,

================================================================================
QUESTION: What are the foundations needed for AI?

SOURCE 1 | PDF PAGE 5
------------------------------------------------------------
Digital Progress and
Trends Report 2025
Strengthening AI Foundations

SOURCE 2 | PDF PAGE 24
------------------------------------------------------------
use AI for lesson planning, nurses for patient tracking, contact center agents for coaching,
and farmers for agronomic advice. In these roles, AI acts more as a co-worker or coach—
enhancing human capacity—than a replacement.
 ◦ However, the scale, equity, and sustainability of benefits hinge on the 4Cs.
AI definitions, ecosystem, and significant trends
Artificial intelligence  (AI) is a branch of computer science dedicated to creating systems capable
of performing tasks that typically require human intelligence. Although the concept dates to the
1950s, in recent years, AI capabilities have improved significantly due to the availability of massive
data, better training data, and more powerful computer hardware.
AI is an umbrella term used for a set of loosely related technologies. No consensus exists on what
is and is not AI (Narayanan and Kapoor 2024). As technological capabilities grow, tasks once

================================================================================
QUESTION: What factors affect AI adoption?

SOURCE 1 | PDF PAGE 40
------------------------------------------------------------
than 6 percent of firms are currently using AI-related technologies.
Adoption is concentrated among very large firms; those in “superstar” cities; and businesses
owned by younger, more educated individuals. Recent data from the Business Trends and
Outlook Survey (BTOS) indicate a modest increase in AI adoption, from 3.7 percent in
September 2023 to an expected 6.6 percent by fall 2024 (Bonney et al. 2024). Among developing
countries, 13 percent of firms in Brazil use AI, nearly twice the 6 percent and 7 percent in
Türkiye and Colombia, respectively. AI adoption is higher for firms with more than 1,000
employees. Nearly 60 percent of firms in India, 50 percent of those in China, and 47 percent
of those in Latin America report actively deploying AI, based on the IBM Global AI Adoption
Survey 2023 (IBM 2024).
Firms in IT, professional services, and financial services are most likely to adopt AI. The US BTOS

SOURCE 2 | PDF PAGE 40
------------------------------------------------------------
shows that more than 20 percent of firms in IT services use AI, followed by about 17 percent in
professional services and 9 percent in finance and insurance (Bonney et al. 2024). The IBM Global
AI Adoption Survey 2023 and McKinsey’s GenAI adoption survey show similar results (McKinsey
2025). These three industries tend to top all other industries in the share of workers with advanced
degrees, average earnings, and dependence on digital inputs, and they show high trade intensity.
Thus, they are at the forefront of AI adoption.

In [43]:
evaluation_results = []

for question in evaluation_questions:
    r1 = retrieve_with_index(question, chunks_1, index_1, k=1)[0]
    r2 = retrieve_with_index(question, chunks_2, index, k=1)[0]

    evaluation_results.append({
        "Question": question,
        "Fixed-size Distance": round(r1["distance"], 4),
        "Recursive Distance": round(r2["distance"], 4),
        "Lower Distance": (
            "Fixed-size"
            if r1["distance"] < r2["distance"]
            else "Recursive"
        )
    })

evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df

,Question,Fixed-size Distance,Recursive Distance,Lower Distance
0,What is artificial intelligence?,1.4968,0.7694,Recursive
1,What are the main applications of artificial i...,1.5462,0.9058,Recursive
2,What are the challenges of artificial intellig...,1.4594,0.8886,Recursive
3,How is AI used in different sectors?,1.4107,0.7300,Recursive
4,What are the foundations needed for AI?,1.2131,0.7497,Recursive
5,What factors affect AI adoption?,1.4107,0.7528,Recursive